"""
Streamlit UI for the RAG Music Assistant.

Run with:
    streamlit run src/app.py

Shows the natural-language assistant plus a transparency panel: the detected
preferences, the retrieved candidate songs (the grounding context), and the
guardrail verdict for the generated answer.
"""
import logging

import streamlit as st

from src.assistant import recommend
from src.recommender import load_songs

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")

SONGS_PATH = "data/songs.csv"


@st.cache_data
def get_songs():
    return load_songs(SONGS_PATH)


def main() -> None:
    st.set_page_config(page_title="Music Assistant", page_icon="🎵")
    st.title("🎵 RAG Music Assistant")
    st.caption(
        "Describe what you want to hear. The app retrieves matching songs from the "
        "catalog, an LLM writes a grounded recommendation, and a guardrail checks it."
    )

    songs = get_songs()
    query = st.text_input(
        "What would you like to hear?",
        placeholder="e.g. high energy pop for the gym",
    )
    k = st.slider("Candidates to retrieve", min_value=3, max_value=10, value=5)

    if st.button("Recommend", type="primary") and query.strip():
        with st.spinner("Retrieving and generating..."):
            result = recommend(query, songs, k=k)

        st.subheader("Recommendation")
        st.write(result["answer"])

        col1, col2 = st.columns(2)
        col1.metric("Confidence", f"{result['confidence']['score']:.2f}")
        col2.metric("Source", result["source"])
        st.caption(result["confidence"]["reason"])

        if result["source"] == "llm":
            st.success("Answer generated by the LLM and passed the grounding guardrail.")
        else:
            reason = result["fallback_reason"] or "guardrail rejected the LLM answer"
            st.warning(f"Fell back to a safe rule-based answer ({reason}).")

        with st.expander("How this answer was built (transparency)"):
            st.markdown(f"**Detected preferences:** `{result['prefs']}`")
            if result["validation"]:
                st.markdown(f"**Guardrail:** `{result['validation']}`")
            st.markdown("**Retrieved candidates (the grounding context):**")
            st.dataframe(
                [
                    {
                        "Title": c["title"],
                        "Artist": c["artist"],
                        "Genre": c["genre"],
                        "Mood": c["mood"],
                        "Energy": c["energy"],
                        "Score": round(c["score"], 2),
                    }
                    for c in result["candidates"]
                ],
                hide_index=True,
            )


if __name__ == "__main__":
    main()
